### PR TITLE
fix: Error: error:0308010C:digital envelope routines::unsupported

### PR DESCRIPTION
**Pull request by mainarthur**
PR fixing #59  Issue

hash.js was used by ethers.js in https://github.com/ethers-io/ethers.js/releases/tag/v5.7.0 / https://github.com/ethers-io/ethers.js/commit/450694e25760d383f3fe3b299d181ebe5fd6ab06 

@junderw  @d-yokoi

### CODE REVIEW

**Comment by sisou** [comment]
It was solves with the `ripemd160` package in bitcoinjs-lib: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1812

**Comment by mainarthur** [comment]
> It was solved with the ripemd160 package in bitcoinjs-lib: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1812

but this issue wasn't solved in this package

**Comment by sisou** [comment]
Correct. I meant to say that that 'official' fix is using another dependency for the fix. I'm also waiting for this package to get updated.

**Comment by mainarthur** [comment]
I've changed the package to ripemd160 :)

**Comment by junderw** [comment]
I forgot about this PR, and just fixed it in the new published version.

Fixed.

Thanks for the PR!

**Pull request closed without merging**
