### PR TITLE
chore: upgrade wif to v4.0.0

### PR DESCRIPTION
**Pull request by ChrisCho-H**
update wif following https://github.com/bitcoinjs/wif/pull/30
this will prevent error caused by crypto libs in browser or mobile

### CODE REVIEW

**Comment by junderw** [comment]
I would rather remove wif.

In a BIP32 world, wif is unnecessary.

Even if you need it, you can always do `wif.encode(node.privateKey)`

**Comment by ChrisCho-H** [comment]
bip32 has a function `toWIF()` which has a dependency on wif.
do u think that module is also better to be removed?

**Comment by junderw** [comment]
Yes, that is what I meant when I said we should remove it.

It would be a breaking change, so I've been putting it off, I should have removed it when we updated for taproot.

**Comment by ChrisCho-H** [comment]
I made PR https://github.com/bitcoinjs/bip32/pull/82 to remove wif

**Pull request closed without merging**
