### PR TITLE
Fix solve the problem of 'rmd160' hash not supported under 'electron' #13

### PR DESCRIPTION
**Pull request by ontheroad1992**

### CODE REVIEW

**Comment by junderw** [comment]
Why would you solve this problem here?

Solving this problem in Electron is easier and will fix the problem for every library that uses ripemd160.

**Comment by ontheroad1992** [comment]
> 在Electron中解决此问题更容易，并将解决每个使用ripemd160的库的问题。

Since 'electronic' doesn't support rmd160, if I want to use it correctly, I need to modify it in 'node_modules', but my development dependencies have been updated or added, I need to re-edit the 'node_modules' code, which is very troublesome. If I can modify it directly in 'bip32', I don't need to repeat this operation. I can't find a better way now.

**Comment by ontheroad1992** [comment]
> 你为什么要在这里解决这个问题？
> 
> 在Electron中解决此问题更容易，并将解决每个使用ripemd160的库的问题。
在收到您的回复后,我意识到我忽略了'electron'方面的解决办法,所以我查看了'electron'的'Issues'中关于'rmd160'的部分['Hash algorithms available to Electron are severely limited'](https://github.com/electron/electron/issues/16195#issue-394118902),['They switched OpenSSL to BoringSSL'](https://github.com/electron/electron/issues/16195#issuecomment-450990183)
Also provided a solution, but for me, the cost is too high

**Comment by ontheroad1992** [comment]
> 你为什么要在这里解决这个问题？
> 
> 在Electron中解决此问题更容易，并将解决每个使用ripemd160的库的问题。

After receiving your reply, I realized that I ignored the 'electron' solution, so I looked at the 'electron' 'Issues' section on 'rmd160'['Hash algorithms available to Electron are severely limited'](https://github.com/electron/electron/issues/16195#issue-394118902),['They switched OpenSSL to BoringSSL'](https://github.com/electron/electron/issues/16195#issuecomment-450990183)
Also provided a solution, but for me, the cost is too high

Since 'electronic' doesn't support rmd160, if I want to use it correctly, I need to modify it in 'node_modules', but my development dependencies have been updated or added, I need to re-edit the 'node_modules' code, which is very troublesome. If I can modify it directly in 'bip32', I don't need to repeat this operation. I can't find a better way now.If this will cause bad results, I will revoke

**Comment by junderw** [comment]
Please modify the typescript, rebuild, then commit both JS and TS files.

Thanks.

**Pull request closed without merging**
