### PR TITLE
Missing dependency in package.json

### PR DESCRIPTION
**Pull request by schachar**
Missing safe-buffer dependency which is used in index.js

### CODE REVIEW

**Comment by reqshark** [comment]
[`bs58check`](https://github.com/bitcoinjs/bip32/blob/master/package.json#L27) has [that dependency](https://github.com/bitcoinjs/bs58check/blob/master/package.json#L44) so `bip32` gets it from `node_modules`.

i wouldnt want it in package.json, because fewer entries is better than double entries

**Comment by schachar** [comment]
well npm resolves that at install time. and having a missing dependency make break your system if that transient dependency is removed

**Comment by reqshark** [comment]
fast process crash with single missing dependency is ideal. then you know to fix.

on the other hand, putting same dep in multiple places means:
* updating versions across multiple projects?
* or else maybe versions diverge between projects (more insidious, nothing breaks right away)
* extra npm downloading

i think there's a better argument you can make. you could say it's idiomatically (stylistically) more correct to have the project's require calls listed out in package.json.. at least that's the only reason i can think of for why you want to go double-depping

**Comment by junderw** [comment]
Since currently the only supported NodeJS versions for the nodeJS team is >=v6. safe-buffer is no longer necessary. The only reason to keep it around would be "just in case someone is still using <v6 node version."

That being said, this pull request would be nullified either way, so I will go ahead and close this.

**Pull request closed without merging**
